### ISSUE TITLE
python 3 issue

### ISSUE THREAD

**Issue by mjohnste** [ArnesSI/pynetdot#10]
When I try and run code and use python3:
```

Traceback (most recent call last):
  File "netdot_test_api.py", line 1, in <module>
    import pynetdot
  File "/usr/local/lib/python3.4/dist-packages/pynetdot/__init__.py", line 4, in <module>
    from .models import *
  File "/usr/local/lib/python3.4/dist-packages/pynetdot/models/__init__.py", line 3, in <module>
    import base
ImportError: No module named 'base'
```

**Comment by matejv** [comment]
Just an update. I'm looking at this and working on making pynetdot python 3 compatible. There are a number of issues that need to be fixed. I hope to have a working version by the end of the week.

**Comment by matejv** [comment]
I have updated pynetdot to be Python 3 compatible. Version 1.5.0 - also pushed to Pypi, so `pip install -U pynetdot` should be all you need.

I have tested with Python 3.4, so there is possibility of some bugs in later versions. If you find any, please re-open this issue.
